FROM jenkins/jenkins:2.346.1-jdk17-preview
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
RUN mkdir -p /var/jenkins_home/.aws/
COPY eip-enterprise-caf-level0.groovy /usr/local/eip-enterprise-caf-level0.groovy
COPY eip-enterprise-caf-level0.groovy /usr/local/eip-enterprise-caf-level1.groovy
USER root
RUN apt-get clean && apt-get update && apt-get install -y gnupg software-properties-common
RUN apt-get clean && apt-get update
RUN apt-get -y install kubernetes-client
RUN apt-get -y install netcat
RUN apt-get -y install jq
RUN apt-get -y install bash
RUN apt-get -y install unzip
RUN apt-get -y install curl
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN aws --version
RUN apt-get -y install docker
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
RUN apt-get update && apt-get install terraform && terraform -version docker
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp && mv /tmp/eksctl /usr/local/bin && eksctl version
USER jenkins
